[package]
name = "mm-memory"
version = "0.1.0"
edition = "2024"

[dependencies]
neo4rs = "0.7.1"
tokio = { version = "1", features = ["full"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
thiserror = "1.0"
tracing = "0.1"
async-trait = { workspace = true }
