[workspace]
members = ["crates/mm-cli", "crates/mm-core", "crates/mm-memory", "crates/mm-server"]
resolver = "3"
default-members = ["crates/mm-cli"]

[workspace.dependencies]
rust-mcp-sdk = "0.4.2"
async-trait = "0.1"
