[package]
name = "mm-git"
version = "0.1.0"
edition = "2024"
license = "MPL-2.0"

[dependencies]
serde = { workspace = true, features = ["derive"] }
thiserror = { workspace = true }
schemars = { workspace = true }
