[package]
name = "mm-server"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1", features = ["full"] }
rust-mcp-sdk = "0.4.2"
async-trait = "0.1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
