# Default configuration for Middle Manager


[memory]
# Label added to every new entity
default_label = "Memory"
allow_default_relationships = true
allowed_relationships = []
allow_default_labels = true
allowed_labels = []
# Default project to use when not specified
default_project = "andoriyu:project:middle_manager"

[neo4j]
uri = "neo4j://localhost:7687"
username = "neo4j"
password = "password"
