# Default configuration for Middle Manager


[memory]
# Label added to every new entity
default_label = "Memory"
default_relationships = true
additional_relationships = []
default_labels = true
additional_labels = []

[neo4j]
uri = "neo4j://localhost:7687"
username = "neo4j"
password = "password"
