[package]
name = "mm-utils"
version = "0.1.0"
edition = "2024"
license = "MPL-2.0"

[dependencies]
arbitrary = { workspace = true }
arbtest = { workspace = true }
tokio = { workspace = true, features = ["rt"] }
schemars = { workspace = true }
serde_json = { workspace = true }

[dev-dependencies]
