name: CI

on:
  pull_request:
  workflow_dispatch:

jobs:
  fmt:
    name: Rustfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
          components: rustfmt
      - uses: Swatinem/rust-cache@v2
      - name: Rustfmt Check
        uses: actions-rust-lang/rustfmt@v1

  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
          components: clippy
      - uses: Swatinem/rust-cache@v2
      - uses: clechasseur/rs-clippy-check@v4
        with:
          args: --workspace --all-targets -- -D warnings

  test:
    name: Tests
    runs-on: ubuntu-latest
    env:
      MM_NEO4J__URI: "neo4j://localhost:${{ job.services.neo4j.ports['7687'] }}"
    services:
      neo4j:
        image: neo4j:5.15.0
        ports:
          - 7475:7474
          - 7688:7687
        env:
          NEO4J_AUTH: neo4j/password
          NEO4J_PLUGINS: '["apoc"]'
          NEO4J_apoc_export_file_enabled: 'true'
          NEO4J_apoc_import_file_enabled: 'true'
          NEO4J_apoc_import_file_use__neo4j__config: 'true'
        options: >-
          --health-cmd "wget --no-verbose --tries=1 --spider http://localhost:7474 || exit 1"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
      - uses: Swatinem/rust-cache@v2
      - uses: taiki-e/install-action@v2
        with:
          tool: cargo-nextest
      - name: Run tests
        run: cargo nextest run --workspace --all-targets --profile ci --no-fail-fast
      - name: Upload junit report
        uses: actions/upload-artifact@v4
        with:
          name: junit-report
          path: target/nextest/ci/junit.xml
      - name: Test Summary
        uses: test-summary/action@v2
        with:
          paths: "target/nextest/ci/junit.xml"
        if: always()
