name: CI

on:
  pull_request:
  workflow_dispatch:

jobs:
  fmt:
    name: Rustfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
          components: rustfmt
      - uses: Swatinem/rust-cache@v2
      - name: Rustfmt Check
        uses: actions-rust-lang/rustfmt@v1

  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
          components: clippy
      - uses: Swatinem/rust-cache@v2
      - uses: clechasseur/rs-clippy-check@v4
        with:
          args: --workspace --all-targets -- -D warnings

  check:
    name: Cargo Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
      - uses: Swatinem/rust-cache@v2
      - name: Cargo check
        run: cargo check --workspace --all-targets

  test:
    name: Tests
    runs-on: ubuntu-latest
    env:
      MM_NEO4J__URI: neo4j://localhost:7688
      MM_NEO4J__USERNAME: neo4j
      MM_NEO4J__PASSWORD: password
    steps:
      - uses: actions/checkout@v4
      - name: Start services
        run: docker compose up -d
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
          rustflags: ""
      - uses: Swatinem/rust-cache@v2
      - uses: taiki-e/install-action@v2
        with:
          tool: cargo-nextest
      - name: Run tests
        run: cargo nextest run --workspace --all-targets --profile ci --no-fail-fast
      - name: Upload junit report
        uses: actions/upload-artifact@v4
        with:
          name: junit-report
          path: target/nextest/ci/junit.xml
      - name: Test Summary
        uses: test-summary/action@v2
        with:
          paths: "target/nextest/ci/junit.xml"
        if: always()
